from fastapi import FastAPI
from pydantic import BaseModel

from database import create_table, save_document
from ai_core.gemini_generator import generate_legal_document


app = FastAPI(title="LegalEase API")


# Create database table
create_table()


class DocumentRequest(BaseModel):

    document_type: str
    parties: str
    terms: str
    effective_date: str


@app.get("/")
def home():

    return {
        "message": "LegalEase API is running"
    }


@app.post("/generate")
def generate_document(
    request: DocumentRequest
):

    try:

        # Generate document using Gemini
        document = generate_legal_document(

            request.document_type,

            request.parties,

            request.terms,

            request.effective_date
        )


        # Save generated document
        save_document(

            request.document_type,

            request.parties,

            request.terms,

            request.effective_date,

            document
        )


        return {

            "success": True,

            "document": document,

            "message":
                "Document generated by Gemini and saved to database"
        }


    except Exception as error:

        print(
            "GEMINI ERROR:",
            repr(error)
        )

        return {

            "success": False,

            "error": str(error)
        }